---
# Default variables for Docker installation
docker_version: "latest"
docker_users:
  - "{{ ansible_user }}"
docker_daemon_options:
  hosts:
    - "unix:///var/run/docker.sock"
    - "tcp://0.0.0.0:2376"
  tls: true
  tlsverify: true
  tlscacert: "/etc/docker/ca.pem"
  tlscert: "/etc/docker/server-cert.pem"
  tlskey: "/etc/docker/server-key.pem"
  data-root: "/var/lib/docker"  # Explicitly set to use our dedicated partition
docker_insecure_registries: []
docker_storage_driver: "overlay2"
docker_verify_mounts: true  # Verify that /var/lib/docker is properly mounted
