---
all:
  hosts:
    ser8:
      ansible_host: "{{ ser8_host | default('ser8-hostname') }}"
      ansible_user: "{{ ser8_user | default('k3sadmin') }}"
      ansible_ssh_private_key_file: "{{ ssh_key_path | default('~/.ssh/id_ed25519') }}"

